linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/newcore-network/opencore-cli

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
